@echo off
setlocal EnableDelayedExpansion
REM ============================================================================
REM  GeoStream -- Nairobi Urban Flood Digital Twin
REM  Pipeline Directory Initializer  (Windows batch)
REM
REM  Creates the complete GeoStream folder tree.
REM  Safe to re-run: every mkdir is guarded with "if not exist".
REM
REM  USAGE
REM  -----
REM  cd /d C:\Users\Admin\Desktop\nairobi-flood-digital-twi
REM  init_data_folders.bat
REM ============================================================================

echo.
echo ================================================================
echo   GeoStream ^| Nairobi Flood Digital Twin
echo   Pipeline Directory Initializer
echo   Target: 16 GB RAM constraint - chunked / masked layout
echo ================================================================
echo.

REM ── Guard: must be run from the repo root ────────────────────────────────────
if not exist "MEMORY_CONSTRAINTS.md" (
    echo [ERROR] Run this script from the repository root.
    echo         Expected MEMORY_CONSTRAINTS.md in current folder.
    exit /b 1
)

REM ============================================================================
REM  STEP 1 -- RAW DATA VAULT
REM ============================================================================
echo [1/6] Scaffolding raw data vault ...

if not exist "data\raw\terrain"  mkdir "data\raw\terrain"
if not exist "data\raw\assets"   mkdir "data\raw\assets"
if not exist "data\raw\climate"  mkdir "data\raw\climate"
if not exist "data\raw\vectors"  mkdir "data\raw\vectors"

REM  Write README stubs via PowerShell to avoid cmd.exe parenthesis conflicts
if not exist "data\raw\terrain\README.txt" (
    powershell -Command "Set-Content 'data\raw\terrain\README.txt' 'Place the 4 USGS SRTM GeoTIFF tiles here.`nNaming convention: srtm_TILE_nairobi.tif`nThese files are NEVER modified by pipeline code.'"
)

if not exist "data\raw\assets\README.txt" (
    powershell -Command "Set-Content 'data\raw\assets\README.txt' 'Place Google Open Buildings footprint files here.`nAccepted formats: .csv, .geojson, .parquet'"
)

if not exist "data\raw\climate\README.txt" (
    powershell -Command "Set-Content 'data\raw\climate\README.txt' 'Place CHIRPS daily rainfall timeline files here.`nAccepted formats: .nc (NetCDF), .tif (GeoTIFF)'"
)

if not exist "data\raw\vectors\README.txt" (
    powershell -Command "Set-Content 'data\raw\vectors\README.txt' 'Place UNOSAT flood boundary shapefiles here.`nAccepted formats: .shp + sidecar files, .geojson, .gpkg'"
)

REM ============================================================================
REM  STEP 2 -- PROCESSED / ENGINEERED DATA
REM ============================================================================
echo [2/6] Scaffolding processed artefact directories ...

if not exist "data\processed\arrays"  mkdir "data\processed\arrays"
if not exist "data\processed\masked"  mkdir "data\processed\masked"

if not exist "data\processed\arrays\README.txt" (
    powershell -Command "Set-Content 'data\processed\arrays\README.txt' 'Stores extracted numpy matrices (.npy, .npz, .zarr).`nPrimary artefacts: slope_nairobi.npy, twi_nairobi.npy`nAll arrays should be float32 to halve RAM vs float64.`nMemory-map with: np.load(path, mmap_mode=r)'"
)

if not exist "data\processed\masked\README.txt" (
    powershell -Command "Set-Content 'data\processed\masked\README.txt' 'Chunked array domains with always-dry pixels removed.`nGenerated by src/preprocessing/srtm_mosaic.py after applying the always-dry mask.`nFormat: zarr chunk store preferred; fallback to .npy slabs.'"
)

REM ============================================================================
REM  STEP 3 -- STATIC BASEMAPS
REM ============================================================================
echo [3/6] Creating static basemap cache directory ...

if not exist "data\static_basemaps" mkdir "data\static_basemaps"

if not exist "data\static_basemaps\README.txt" (
    powershell -Command "Set-Content 'data\static_basemaps\README.txt' 'Cached local basemap images for Pydeck canvas rendering.`nGenerate via: python -m src.ingestion.fetch_basemaps`nFormats: .png (full quality) or .webp (compressed, preferred).`nThese files are gitignored -- regenerate on each new machine.'"
)

REM ============================================================================
REM  STEP 4 -- MODEL CHECKPOINTS
REM ============================================================================
echo [4/6] Scaffolding model checkpoint directories ...

if not exist "models\autoencoder"  mkdir "models\autoencoder"
if not exist "models\time_series"  mkdir "models\time_series"

if not exist "models\autoencoder\README.txt" (
    powershell -Command "Set-Content 'models\autoencoder\README.txt' 'Checkpoint files for the spatial feature autoencoder.`nNaming convention: ae_epochN_lossL.pt`nBest checkpoint: models/autoencoder/best.pt'"
)

if not exist "models\time_series\README.txt" (
    powershell -Command "Set-Content 'models\time_series\README.txt' 'Checkpoint files for the recursive LSTM model.`nNaming convention: lstm_epochN_valRMSE.pt`nBest checkpoint: models/time_series/best.pt'"
)

REM ============================================================================
REM  STEP 5 -- SOURCE PACKAGE SKELETON
REM ============================================================================
echo [5/6] Extending src\ with preprocessing sub-package ...

if not exist "src\preprocessing" mkdir "src\preprocessing"

for %%d in (src src\ingestion src\preprocessing src\models src\dashboard src\utils) do (
    if not exist "%%d\__init__.py" (
        powershell -Command "Set-Content '%%d\__init__.py' '# GeoStream package marker'"
    )
)

REM ============================================================================
REM  STEP 6 -- .gitkeep SEEDS
REM ============================================================================
echo [6/6] Seeding .gitkeep files in empty leaf directories ...

for %%d in (data\raw\terrain data\raw\assets data\raw\climate data\raw\vectors data\processed\arrays data\processed\masked data\static_basemaps models\autoencoder models\time_series) do (
    if not exist "%%d\.gitkeep" type nul > "%%d\.gitkeep"
)

REM ============================================================================
REM  SUMMARY
REM ============================================================================
echo.
echo ================================================================
echo   GeoStream directory tree created successfully!
echo ================================================================
echo.
echo   data\raw\terrain\       -- 4 USGS SRTM GeoTIFF tiles
echo   data\raw\assets\        -- Google Open Buildings footprints
echo   data\raw\climate\       -- CHIRPS daily rainfall timelines
echo   data\raw\vectors\       -- UNOSAT flood boundary shapefiles
echo   data\processed\arrays\  -- numpy slope / TWI matrices (float32)
echo   data\processed\masked\  -- always-dry-masked chunked domains
echo   data\static_basemaps\   -- cached Pydeck basemap graphics
echo   models\autoencoder\     -- spatial encoder checkpoints
echo   models\time_series\     -- LSTM weights
echo   src\preprocessing\      -- mosaic, slope, TWI, masking
echo.
echo   Next step:
echo     python -m src.preprocessing.srtm_mosaic --help
echo.

endlocal
